################################################################################
# Primetime: TF reporter pipeline
# Vinícius H. Franceschini-Santos, Max Trauernicht 
# =============================================================================
# ============================ Config file  ===================================
# =============================================================================

#==============================================================================
INPUT_DATA:
  U2OS_control:
    is_pdna: False
    condition: DMSO
    fastq: 
      - test_data/U2OS_DMSO_1.fastq.gz

  U2OS_calcitriol:
    is_pdna: False
    condition: Calcitriol
    fastq: 
      - test_data/U2OS_calcitriol_1.fastq.gz
      - test_data/U2OS_calcitriol_2.fastq.gz
      - test_data/U2OS_calcitriol_3.fastq.gz

  pDNA:
    is_pdna: True
    condition: None
    fastq: 
      - test_data/pDNA_1.fastq.gz
      - test_data/pDNA_2.fastq.gz
# ==============================================================================
COMPARATIVE_ANALYSIS:
  REFERENCE_CONDITION: DMSO
  CONTRAST_CONDITION: Calcitriol

# =============================================================================
OUTPUT_DIRECTORY: test_data_output_pDNA_v2


# ==============================================================================
# ============================ Pipeline parameters =============================
PVALUE_THRESHOLD: 0.01


# ==============================================================================
# ============================ Library parameters ==============================
# Number of barcodes per TF
BARCODES_PER_TF: 5

# Length of the barcodes
BARCODE_LENGTH: 12

# BC downstream sequence: this will be used to identify the barcodes in the fastq files
BARCODE_DOWNSTREAM_SEQUENCE: CATCGTCGCATCCAAGAGGCTAGCTAACTA 

# How many mismatches are allowed in the downstream sequence to identify the barcode?
MAX_MISMATCH_DOWNSTREAM_SEQ: 3

# Path to the barcode annotation file
BARCODE_ANNOTATION_FILE: misc/bc_annotation_prime_v2.csv

# Path to expected pDNA counts, to compare with as a QC
EXPECTED_PDNA_COUNTS: misc/expected_pDNA_counts.txt